Added step to create and show SSH keys

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -8,10 +8,52 @@ app:
   #- branch_to_build: ""
   #- package: ""
   #- mainActivity: ""
+  #- emailForSSHKey: ""
   - debug: "1"
   - emulator_name: "Nexus_5_API_22"
+  - emailForSSHKey: "sudhanshu@leftshift.io"
   
 workflows:
+
+  setup-ssh:
+    steps:
+    - script:
+        title: setup ssh keys
+        inputs:
+        - content: |-
+            #!/bin/bash
+
+            set -e
+
+            if [ ${debug} == "1" ];then
+              set -v
+            fi
+
+            # Check if email has been defined by the user
+            if [ "${emailForSSHKey}" != "" ]; then
+              # TODO : Allow the user to add the keys to a non default place
+              # Check if an id_rsa already exists at the defualt location
+              if [ ! -f ~/.ssh/id_rsa ]; then
+                echo File does not exist at ~/.ssh/id_rsa
+                echo -ne '\n' | ssh-keygen -t rsa -b 4096 -C "${emailForSSHKey}"
+
+                # Show the created keys on the screen
+                ID_RSA=$(<~/.ssh/id_rsa)
+                ID_RSA_PUB=$(<~/.ssh/id_rsa.pub)
+
+                printf "id_rsa\n"
+                printf "%s" "${ID_RSA}"
+                printf "\n\nid_rsa.pub\n"
+                printf "%s" "${ID_RSA_PUB}"
+
+              else
+                echo Looks like an id_rsa already exists at ~/.ssh/id_rsa
+                exit 1
+              fi
+            else
+              echo Parameter "emailForSSHKey" not found
+              exit 1
+            fi
 
   devices:
     steps:
@@ -204,3 +246,4 @@ workflows:
                 echo Package name not found
               fi
             fi
+
