Fixed formatting and added colours for the command git-pull

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -12,7 +12,7 @@ app:
   - emulatorName: "Nexus_5_API_22"
   #- emailForSSHKey: "sudhanshu@leftshift.io"
   - gitRepositoryURL: ""
-  - gitRepositoryBranch: ""
+  - gitRepositoryBranch: "develop"
   
 workflows:
 
@@ -229,14 +229,51 @@ workflows:
         - content: |-
             #!/bin/bash
 
-            set -e
+            # Turning this off, because this ends the script if 0 get returned anywhere
+            # set -e
 
+            # This is for font color and style adjustment
+            RED='\033[0;31m'
+            GREEN='\033[0;32m'
+            BLUE='\033[0;34m'
+            NOCOLOR='\033[0m'
+            BOLD=$(tput bold)
+            NORMAL=$(tput sgr0)            
+
+            # An empty space to separate from the preceeding block
             if [ ${debug} == "1" ];then
               set -v
             fi
 
-            echo Pulling branch ${gitRepositoryBranch}
-            git pull origin ${gitRepositoryBranch}
+            # An empty space to separate from the preceeding block
+            printf "\n"
+
+            # Make a TIMESHTAMP for log file
+            TIMESHTAMP=$(date +%Y%m%d%H%M%S)
+
+            # Check if the branch name is defined
+            # TODO : Automatically pick the current branch
+            if [ "${gitRepositoryBranch}" != "" ]; then
+
+              printf "Alright, let's ${GREEN}pull${NOCOLOR} the ${gitRepositoryBranch} branch for this repo\n\n"
+            
+              # Alright, let's pull
+              git pull origin ${gitRepositoryBranch} 2>&1 | tee git-pull-$TIMESHTAMP.log
+
+              PULL_RESULTS=$(<git-pull-$TIMESHTAMP.log)
+              if [ "$(printf "${PULL_RESULTS}" | grep "fatal" -c)" -gt "0" ]; then
+                printf "\n${BOLD}Error!${NORMAL} Something went wrong with the pull, you should look this up\n\n"
+                exit 1
+              else
+                # All done
+                printf "\nAll done ${GREEN}baby!${NOCOLOR}.\n\n"
+                exit 0
+              fi
+
+            else
+              printf "${BOLD}Error!${NORMAL} Dude, you need to add the ${BLUE}gitRepositoryBranch${NOCOLOR} for this to work\n\n"
+              exit 1
+            fi
 
   assemble-fast:
     before_run:
