Created action to archive and create an ipa for iOS [20m0s]

diff --git a/upshift b/upshift
--- a/upshift
+++ b/upshift
@@ -727,14 +727,13 @@ function XCPretty {
         ShowError
         printf "Alright, so it seems we need to install xcpretty and that requires\nadmin permissions. You need to add  ${redColour}masterPassword${noColour} to your config\nfor this to work.\nYou can get a sample config by running upshift setup config"
         next=false
-        exit 1
       fi
     else
       # User should type in the password
       sudo -S gem install xcpretty
+      printf "\nXCPretty is now ${greenColour}installed${noColour}, one less thing to think about! 🍺\n\n"
     fi
 
-    printf "\nXCPretty is now ${greenColour}installed${noColour}, one less thing to think about! 🍺\n\n"
   else
     printf "Woot! XCPretty is already installed\n"
   fi
@@ -850,53 +849,13 @@ function BuildiOS {
     # TODO : Clean the effing thing before you start
     printf "Compiling the beautiful codebase\n\n"
 
-    #set -o pipefail && xcodebuild -"${PROJECT_TYPE}" "${PROJECT_PATH}" -scheme "${scheme}" -hideShellScriptEnvironment -sdk iphonesimulator -destination "platform=iphonesimulator,name=${iPhone}" -derivedDataPath build | tee "xcode-build-${TIMESHTAMP}.log" | xcpretty
-
-    set -o pipefail && xcodebuild -"${PROJECT_TYPE}" "${PROJECT_PATH}" -scheme "${scheme}" -derivedDataPath build -archivePath "build/${projectName}.xcarchive" archive | tee "xcode-build-${TIMESHTAMP}.log" | xcpretty
+    set -o pipefail && xcodebuild -"${PROJECT_TYPE}" "${PROJECT_PATH}" -scheme "${scheme}" -hideShellScriptEnvironment -sdk iphonesimulator -destination "platform=iphonesimulator,name=${iPhone}" -derivedDataPath build | tee "xcode-build-${TIMESHTAMP}.log" | xcpretty
 
     BUILD_RESULTS=$(<"xcode-build-${TIMESHTAMP}.log");
     BUILD_SUCCEDED=$(grep "BUILD SUCCEEDED" -c <<< "${BUILD_RESULTS}")
-    ARCHIVE_SUCCEDED=$(grep "ARCHIVE SUCCEEDED" -c <<< "${BUILD_RESULTS}")
 
-    if [ "${BUILD_SUCCEDED}" -gt 0 ] || [ "${ARCHIVE_SUCCEDED}" -gt 0 ]; then
-      # The build or archive succeded
-
-      # Get the UUID from profiles
-      # https://gist.github.com/mxpr/8208289a63ca4e3a35a4
-      # Loop through all files, if you get a UDID, add them to the list of profiles
-      if [ -d "./profiles/" ]; then
-        # The profiles folder exists
-        for profileName in profiles/*.mobileprovision; do
-          uuid=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< $(security cms -D -i "${profileName}" 2>/dev/null))
-
-          # If a UUID exist, then copy it, if it hasn't already been copied
-          if [ "${uuid}" != "" ]; then
-            # Copy file to UUID folder
-            `cp -f ${profileName} ~/Library/MobileDevice/Provisioning\ Profiles/${uuid}.mobileprovision`
-            printf "Copies provisioning file ${uuid}.mobileprovision to the system\n"
-          fi
-
-        done
-      else
-        ShowError
-        printf "You need to add your provisioning profiles to a folder called profiles\n\n"
-        next=false
-        exit
-      fi
-
-
-      # Create an IPA (Export the effing thing)
-      set -o pipefail && xcodebuild -exportArchive -exportOptionsPlist "profiles/export.plist" -archivePath "build/${projectName}.xcarchive" -exportPath "build/${projectName}.ipa" 2>&1 | tee "xcode-archive-${TIMESHTAMP}.log" | xcpretty
-
-      EXPORT_RESULTS=$(<"xcode-archive-${TIMESHTAMP}.log")
-      EXPORT_SUCCEDED=$(grep "EXPORT SUCCEDED" -c <<< "${EXPORT_RESULTS}")
-
-      if [ "${EXPORT_SUCCEDED}" -gt 0 ]; then
-        printf "Export Succeded\n"
-      else
-        printf "${EXPORT_RESULTS}\n\n"
-      fi
-
+    if [ "${BUILD_SUCCEDED}" -gt 0 ]; then
+      # The build succeded
       printf "The build was ${greenColour}successful${noColour} 🍺\n\n"
     else
       ShowError
@@ -910,6 +869,120 @@ function BuildiOS {
     xcodebuild -list
     next=false
   fi
+}
+
+##
+## Archive iOS
+##
+
+function ArchiveIOS {
+
+  StartAction "ArchiveIOS"
+
+  # If 'next' is false, exit
+  if [ ${next} == false ]; then
+    ShowPreviousFailed
+    return
+  fi
+
+  # Make a TIMESHTAMP for log file
+  TIMESHTAMP=$(date +%Y%m%d%H%M%S)
+
+  # Either use projectName defined by the user, or pick it automatically
+  if [ "${projectName}" == "" ]; then
+    printf "Dude, you need to define ${redColour}projectName${noColour} in your config.\nSince you haven't, we are going to pick it automatically,\nwhich will take time on every build.\n\n"
+
+    PROJECT_NAME_STRING=$(xcodebuild -showBuildSettings | grep PROJECT_NAME)
+    projectName=${PROJECT_NAME_STRING#"    PROJECT_NAME = "}
+
+    if [ "${projectName}" == "" ]; then
+      ShowError
+      printf "Damn, couldn't even find it automatically. Are you sure this is an iOS repo?\n"
+      next=false
+      return
+    fi
+
+    printf "Found ${blueColour}${projectName}${noColour} automatically. Using this now.\n\n"
+  fi
+
+  # Build using workspace if user asks, if it uses cocoapods user workspace automatically, othewise use xcodeproj
+  PROJECT_TYPE="project"
+  EXTENSION=".xcodeproj"
+
+  if [ "${useWorkspace}" == true ]; then
+    # Since the user is requesting for it, decision is done, we love our users.
+    PROJECT_TYPE="workspace"
+    EXTENSION=".xcworkspace"
+  else
+    if [ -f "Podfile" ]; then
+      # If a Podfile exits, then guys use Cocoapods, load up the workspace by default
+      PROJECT_TYPE="workspace"
+      EXTENSION=".xcworkspace"
+    fi
+  fi
+
+  PROJECT_PATH="${projectName}${EXTENSION}";
+
+  if [ "${scheme}" != "" ]; then
+
+    set -o pipefail && xcodebuild -"${PROJECT_TYPE}" "${PROJECT_PATH}" -scheme "${scheme}" -derivedDataPath build -archivePath "build/${projectName}.xcarchive" archive | tee "xcode-archive-${TIMESHTAMP}.log" | xcpretty
+
+    ARCHIVE_RESULTS=$(<"xcode-archive-${TIMESHTAMP}.log");
+    ARCHIVE_SUCCEDED=$(grep "ARCHIVE SUCCEEDED" -c <<< "${ARCHIVE_RESULTS}")
+
+    if [ "${ARCHIVE_SUCCEDED}" -gt 0 ]; then
+      # The archive succeded
+
+      # Get the UUID from profiles
+      # https://gist.github.com/mxpr/8208289a63ca4e3a35a4
+      # Loop through all files, if you get a UDID, add them to the list of profiles
+      if [ -d "./profiles/" ]; then
+        # The profiles folder exists
+        for profileName in profiles/*.mobileprovision; do
+          uuid=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< $(security cms -D -i "${profileName}" 2>/dev/null))
+
+          # If a UUID exist, then copy it, if it hasn't already been copied
+          if [ "${uuid}" != "" ]; then
+            # Copy file to UUID folder
+            `cp -f ${profileName} ~/Library/MobileDevice/Provisioning\ Profiles/${uuid}.mobileprovision`
+            printf "Copy provisioning file ${uuid}.mobileprovision to the system\n"
+          fi
+
+        done
+      else
+        ShowError
+        printf "You need to add your provisioning profiles to a folder called profiles\n\n"
+        next=false
+        exit
+      fi
+
+
+      # Create an IPA (Export the effing thing)
+      printf "Create an IPA\n"
+      set -o pipefail && xcodebuild -exportArchive -exportOptionsPlist "profiles/export.plist" -archivePath "build/${projectName}.xcarchive" -exportPath "build/${projectName}.ipa" 2>&1 | tee "xcode-archive-${TIMESHTAMP}.log" | xcpretty
+
+      EXPORT_RESULTS=$(<"xcode-archive-${TIMESHTAMP}.log")
+      EXPORT_SUCCEDED=$(grep "EXPORT SUCCEDED" -c <<< "${EXPORT_RESULTS}")
+
+      if [ "${EXPORT_SUCCEDED}" -gt 0 ]; then
+        printf "The build was ${greenColour}successful${noColour} 🍺\n\n"
+      else
+        ShowError
+        printf "It seems the export ${redColour}failed${noColour}. You need to look this up\n\n"
+        next=false
+      fi
+    else
+      ShowError
+      printf "It seems the build ${redColour}failed${noColour}. You need to look this up\n\n"
+      next=false
+    fi
+  else
+    ShowError
+    printf "Dude, you need to define the ${blueColour}scheme${noColour} that you would like to build.\nYou can get a sample config by running upshift setup config\nYou can pick one here\n\n"
+    xcodebuild -list
+    next=false
+  fi
+
 }
 
 ##
@@ -1214,6 +1287,7 @@ function FindJobQueue {
         "XCodeVersion")       jobQueue=("XCodeVersion");;
         "XCPretty")           jobQueue=("XCPretty");;
         "BuildiOS")           jobQueue=("BuildiOS");;
+        "ArchiveIOS")         jobQueue=("ArchiveIOS");;
         "DeployiOSSimulator") jobQueue=("DeployiOSSimulator");;
         "SetupScript")        jobQueue=("SetupScript");;
         "SetupGradle")        jobQueue=("SetupGradle");;
